import lexer.LexerDef

/-! # レキサー C コード生成

文法の終端記号リストと LexerDef に基づいて、C 言語のレキサーコードを生成する。

LR1Generator に依存しない独立モジュール。
終端記号のリストとトークン名の変換関数を引数で受け取る。

- LexerDef のルール名と一致する文法終端記号はパターンマッチで認識
- 一致しない英字終端記号はキーワードリテラルとして扱う
- 一致しない記号終端記号はシンボルリテラルとして扱う
-/

/-- 終端記号の分類 -/
inductive TerminalKind where
  | keyword : TerminalKind    -- 英字で始まる (if, while, id, ...)
  | symbol : TerminalKind     -- 記号文字 (+, *, ==, ...)
  deriving BEq, Repr

/-- 終端記号を分類する -/
def classifyTerminal (t : String) : TerminalKind :=
  match t.toList with
  | c :: _ => if c.isAlpha || c == '_' then .keyword else .symbol
  | [] => .symbol

/-- C の文字列リテラルとしてエスケープする -/
def escapeC (s : String) : String :=
  s.toList.map (fun c => match c with
    | '\\' => "\\\\"
    | '"' => "\\\""
    | '\n' => "\\n"
    | '\t' => "\\t"
    | '\x00' => "\\0"
    | c => c.toString
  ) |> String.join

/-- C の文字リテラル内でエスケープする -/
def escapeCChar (c : Char) : String :=
  match c with
  | '\\' => "\\\\"
  | '\'' => "\\'"
  | '\n' => "\\n"
  | '\t' => "\\t"
  | '\r' => "\\r"
  | '\x00' => "\\0"
  | c => c.toString

/-- CharSet の C 条件式を生成 -/
def charSetCondC (cs : CharSet) (var : String) : String :=
  let conds := cs.ranges.map fun r => match r with
    | .range lo hi => s!"({var} >= '{escapeCChar lo}' && {var} <= '{escapeCChar hi}')"
    | .single c => s!"{var} == '{escapeCChar c}'"
  let joined := " || ".intercalate conds
  let inner := if conds.length > 1 then s!"({joined})" else joined
  if cs.negated then s!"!{inner}" else inner

/-- パターンのマッチ関数 C コードを生成 -/
def generateMatchFn (name : String) (steps : List PatternStep) : String := Id.run do
  let lb := "{"
  let rb := "}"
  let mut code := s!"static int match_{name}(const char *s, int len) {lb}\n"
  code := code ++ "    int pos = 0;\n"
  for step in steps do
    match step with
    | .one cs =>
      code := code ++ s!"    if (pos >= len || !({charSetCondC cs "s[pos]"})) return 0;\n"
      code := code ++ "    pos++;\n"
    | .oneOrMore cs =>
      code := code ++ s!"    if (pos >= len || !({charSetCondC cs "s[pos]"})) return 0;\n"
      code := code ++ "    pos++;\n"
      code := code ++ s!"    while (pos < len && ({charSetCondC cs "s[pos]"})) pos++;\n"
    | .zeroOrMore cs =>
      code := code ++ s!"    while (pos < len && ({charSetCondC cs "s[pos]"})) pos++;\n"
    | .litChar c =>
      code := code ++ s!"    if (pos >= len || s[pos] != '{escapeCChar c}') return 0;\n"
      code := code ++ "    pos++;\n"
    | .litStr str =>
      code := code ++ s!"    if (pos + {str.length} > len || memcmp(s + pos, \"{escapeC str}\", {str.length}) != 0) return 0;\n"
      code := code ++ s!"    pos += {str.length};\n"
  code := code ++ "    return pos;\n"
  code := code ++ s!"{rb}\n\n"
  code

/-- レキサーの C コードを生成する。
    terminals: 文法から収集した終端記号リスト
    toTokName: 終端記号 → C の TOK_XXX 名に変換する関数
    ld: レキサー定義 -/
def generateLexerC (terminals : List String) (toTokName : String → String)
    (ld : LexerDef) : String := Id.run do
  let lb := "{"
  let rb := "}"
  let mut code := ""

  code := code ++ "/* Lexer - Generated by LR1-generator */\n\n"

  -- パターンを持つ終端記号名のリスト
  let patternNames := ld.tokens.toList.map (·.name)

  -- 文法終端記号を分類
  -- パターンあり → パターンで認識
  -- パターンなし + keyword → キーワードリテラル
  -- パターンなし + symbol → シンボルリテラル
  let literalTerminals := terminals.filter (fun t => !patternNames.any (· == t))
  let keywords := literalTerminals.filter (classifyTerminal · == .keyword)
  let symbols := literalTerminals.filter (classifyTerminal · == .symbol)
  let symbols := symbols.toArray.qsort (fun a b => a.length > b.length) |>.toList

  -- マッチ関数の生成（トークンパターン）
  for rule in ld.tokens do
    code := code ++ generateMatchFn rule.name rule.pattern

  -- マッチ関数の生成（スキップパターン）
  for i in List.range ld.skips.size do
    match ld.skips[i]? with
    | some pat => code := code ++ generateMatchFn s!"skip_{i}" pat
    | none => pure ()

  -- Token 構造体
  code := code ++ s!"typedef struct {lb}\n"
  code := code ++ "    int type;\n"
  code := code ++ "    const char *start;\n"
  code := code ++ "    int length;\n"
  code := code ++ "    int line;\n"
  code := code ++ "    int col;\n"
  code := code ++ s!"{rb} LexToken;\n\n"

  -- シンボルテーブル（長い順）
  code := code ++ s!"/* Symbol table (longest first) */\n"
  if symbols.isEmpty then
    code := code ++ s!"#define NUM_SYMBOLS 0\n\n"
  else
    code := code ++ s!"static const struct {lb} const char *str; int len; int token; {rb} symbols[] = {lb}\n"
    for sym in symbols do
      code := code ++ s!"    {lb}\"{escapeC sym}\", {sym.length}, {toTokName sym}{rb},\n"
    code := code ++ s!"{rb};\n"
    code := code ++ s!"#define NUM_SYMBOLS {symbols.length}\n\n"

  -- キーワードテーブル（長さ付き、パターンマッチ後のチェック用）
  code := code ++ s!"/* Keyword table */\n"
  if keywords.isEmpty then
    code := code ++ s!"#define NUM_KEYWORDS 0\n\n"
  else
    code := code ++ s!"static const struct {lb} const char *str; int len; int token; {rb} keywords[] = {lb}\n"
    for kw in keywords do
      code := code ++ s!"    {lb}\"{escapeC kw}\", {kw.length}, {toTokName kw}{rb},\n"
    code := code ++ s!"{rb};\n"
    code := code ++ s!"#define NUM_KEYWORDS {keywords.length}\n\n"

  -- Lexer 構造体
  code := code ++ s!"typedef struct {lb}\n"
  code := code ++ "    const char *source;\n"
  code := code ++ "    int pos;\n"
  code := code ++ "    int length;\n"
  code := code ++ "    int line;\n"
  code := code ++ "    int col;\n"
  code := code ++ s!"{rb} Lexer;\n\n"

  -- lexer_init
  code := code ++ s!"static void lexer_init(Lexer *lex, const char *source, int length) {lb}\n"
  code := code ++ "    lex->source = source;\n"
  code := code ++ "    lex->pos = 0;\n"
  code := code ++ "    lex->length = length;\n"
  code := code ++ "    lex->line = 1;\n"
  code := code ++ "    lex->col = 1;\n"
  code := code ++ s!"{rb}\n\n"

  -- lexer_advance（改行を含むスキップ対応）
  code := code ++ s!"static void lexer_advance(Lexer *lex, int n) {lb}\n"
  code := code ++ s!"    for (int i = 0; i < n; i++) {lb}\n"
  code := code ++ s!"        if (lex->source[lex->pos] == '\\n') {lb}\n"
  code := code ++ "            lex->line++;\n"
  code := code ++ "            lex->col = 1;\n"
  code := code ++ s!"        {rb} else {lb}\n"
  code := code ++ "            lex->col++;\n"
  code := code ++ s!"        {rb}\n"
  code := code ++ "        lex->pos++;\n"
  code := code ++ s!"    {rb}\n"
  code := code ++ s!"{rb}\n\n"

  -- skip_whitespace（lexer ファイルの skip パターン使用）
  code := code ++ s!"static void skip_whitespace(Lexer *lex) {lb}\n"
  code := code ++ s!"    while (lex->pos < lex->length) {lb}\n"
  code := code ++ "        const char *s = lex->source + lex->pos;\n"
  code := code ++ "        int rem = lex->length - lex->pos;\n"
  code := code ++ "        int m;\n"
  if ld.skips.isEmpty then
    code := code ++ "        break;\n"
  else
    for i in List.range ld.skips.size do
      code := code ++ s!"        m = match_skip_{i}(s, rem);\n"
      code := code ++ s!"        if (m > 0) {lb} lexer_advance(lex, m); continue; {rb}\n"
    code := code ++ "        break;\n"
  code := code ++ s!"    {rb}\n"
  code := code ++ s!"{rb}\n\n"

  -- next_token
  code := code ++ s!"static LexToken next_token(Lexer *lex) {lb}\n"
  code := code ++ "    skip_whitespace(lex);\n"
  code := code ++ s!"    LexToken tok = {lb}TOK_EOF, lex->source + lex->pos, 0, lex->line, lex->col{rb};\n\n"
  code := code ++ s!"    if (lex->pos >= lex->length) {lb}\n"
  code := code ++ "        return tok;\n"
  code := code ++ s!"    {rb}\n\n"
  code := code ++ "    const char *start = lex->source + lex->pos;\n"
  code := code ++ "    int remaining = lex->length - lex->pos;\n"
  code := code ++ "    int start_col = lex->col;\n"
  code := code ++ "    int m;\n\n"

  -- シンボルの最長一致
  if !symbols.isEmpty then
    code := code ++ "    /* Symbol (longest match) */\n"
    code := code ++ s!"    for (int i = 0; i < NUM_SYMBOLS; i++) {lb}\n"
    code := code ++ s!"        if (symbols[i].len <= remaining &&\n"
    code := code ++ s!"            memcmp(start, symbols[i].str, symbols[i].len) == 0) {lb}\n"
    code := code ++ "            tok.type = symbols[i].token;\n"
    code := code ++ "            tok.start = start;\n"
    code := code ++ "            tok.length = symbols[i].len;\n"
    code := code ++ "            tok.col = start_col;\n"
    code := code ++ "            lexer_advance(lex, symbols[i].len);\n"
    code := code ++ "            return tok;\n"
    code := code ++ s!"        {rb}\n"
    code := code ++ s!"    {rb}\n\n"

  -- トークンパターン（定義順に試行）
  code := code ++ "    /* Token patterns */\n"
  for rule in ld.tokens do
    code := code ++ s!"    m = match_{rule.name}(start, remaining);\n"
    code := code ++ s!"    if (m > 0) {lb}\n"
    -- キーワードチェック
    if !keywords.isEmpty then
      code := code ++ s!"        /* Check keywords */\n"
      code := code ++ s!"        for (int i = 0; i < NUM_KEYWORDS; i++) {lb}\n"
      code := code ++ s!"            if (keywords[i].len == m && memcmp(start, keywords[i].str, m) == 0) {lb}\n"
      code := code ++ s!"                tok.type = keywords[i].token;\n"
      code := code ++ s!"                tok.start = start;\n"
      code := code ++ s!"                tok.length = m;\n"
      code := code ++ s!"                tok.col = start_col;\n"
      code := code ++ s!"                lexer_advance(lex, m);\n"
      code := code ++ s!"                return tok;\n"
      code := code ++ s!"            {rb}\n"
      code := code ++ s!"        {rb}\n"
    code := code ++ s!"        tok.type = {toTokName rule.name};\n"
    code := code ++ s!"        tok.start = start;\n"
    code := code ++ s!"        tok.length = m;\n"
    code := code ++ s!"        tok.col = start_col;\n"
    code := code ++ s!"        lexer_advance(lex, m);\n"
    code := code ++ s!"        return tok;\n"
    code := code ++ s!"    {rb}\n\n"

  -- 不明な文字
  code := code ++ "    /* Unknown character */\n"
  code := code ++ "    tok.type = -1;\n"
  code := code ++ "    tok.start = start;\n"
  code := code ++ "    tok.length = 1;\n"
  code := code ++ "    tok.col = start_col;\n"
  code := code ++ "    lex->pos++;\n"
  code := code ++ "    lex->col++;\n"
  code := code ++ "    return tok;\n"
  code := code ++ s!"{rb}\n\n"

  -- tokenize 関数
  code := code ++ s!"static int tokenize(const char *source, int length, int *out_tokens, int max_tokens) {lb}\n"
  code := code ++ "    Lexer lex;\n"
  code := code ++ "    lexer_init(&lex, source, length);\n"
  code := code ++ "    int count = 0;\n\n"
  code := code ++ s!"    while (1) {lb}\n"
  code := code ++ "        LexToken tok = next_token(&lex);\n"
  code := code ++ s!"        if (tok.type == TOK_EOF) break;\n"
  code := code ++ s!"        if (tok.type < 0) {lb}\n"
  code := code ++ "            fprintf(stderr, \"Lexer error at line %d, col %d: \"\n"
  code := code ++ "                    \"unexpected '%.*s'\\n\",\n"
  code := code ++ "                    tok.line, tok.col, tok.length, tok.start);\n"
  code := code ++ "            return -1;\n"
  code := code ++ s!"        {rb}\n"
  code := code ++ s!"        if (count >= max_tokens) {lb}\n"
  code := code ++ "            fprintf(stderr, \"Error: too many tokens\\n\");\n"
  code := code ++ "            return -1;\n"
  code := code ++ s!"        {rb}\n"
  code := code ++ "        out_tokens[count++] = tok.type;\n"
  code := code ++ s!"    {rb}\n"
  code := code ++ "    return count;\n"
  code := code ++ s!"{rb}\n"

  code
