/-! # レキサー C コード生成

文法の終端記号リストから、C 言語のレキサーコードを自動生成する。

LR1Generator に依存しない独立モジュール。
終端記号のリストとトークン名の変換関数を引数で受け取る。
-/

/-- 終端記号の分類 -/
inductive TerminalKind where
  | keyword : TerminalKind    -- 英字で始まる (if, while, id, ...)
  | symbol : TerminalKind     -- 記号文字 (+, *, ==, ...)
  deriving BEq, Repr

/-- 終端記号を分類する -/
def classifyTerminal (t : String) : TerminalKind :=
  match t.toList with
  | c :: _ => if c.isAlpha || c == '_' then .keyword else .symbol
  | [] => .symbol

/-- C の文字列リテラルとしてエスケープする -/
def escapeC (s : String) : String :=
  s.toList.map (fun c => match c with
    | '\\' => "\\\\"
    | '"' => "\\\""
    | '\n' => "\\n"
    | '\t' => "\\t"
    | '\x00' => "\\0"
    | c => c.toString
  ) |> String.join

/-- レキサーの C コードを生成する。
    terminals: 終端記号の文字列リスト
    toTokName: 終端記号 → C の TOK_XXX 名に変換する関数 -/
def generateLexerC (terminals : List String) (toTokName : String → String) : String := Id.run do
  let lb := "{"
  let rb := "}"
  let mut code := ""

  -- ヘッダー
  code := code ++ "/* Lexer - Generated by LR1-generator */\n\n"

  -- 終端記号を分類
  let keywords := terminals.filter (classifyTerminal · == .keyword)
  let symbols := terminals.filter (classifyTerminal · == .symbol)
  -- 記号は長い順にソート（最長一致）
  let symbols := symbols.toArray.qsort (fun a b => a.length > b.length) |>.toList

  -- Token 構造体
  code := code ++ s!"typedef struct {lb}\n"
  code := code ++ "    int type;       /* enum Token value */\n"
  code := code ++ "    const char *start;\n"
  code := code ++ "    int length;\n"
  code := code ++ "    int line;\n"
  code := code ++ "    int col;\n"
  code := code ++ s!"{rb} LexToken;\n\n"

  -- キーワードテーブル
  code := code ++ s!"/* Keyword table */\n"
  code := code ++ s!"static const struct {lb} const char *str; int token; {rb} keywords[] = {lb}\n"
  for kw in keywords do
    code := code ++ s!"    {lb}\"{escapeC kw}\", {toTokName kw}{rb},\n"
  code := code ++ s!"{rb};\n"
  code := code ++ s!"#define NUM_KEYWORDS {keywords.length}\n\n"

  -- 記号テーブル（長い順）
  code := code ++ s!"/* Symbol table (longest first) */\n"
  code := code ++ s!"static const struct {lb} const char *str; int len; int token; {rb} symbols[] = {lb}\n"
  for sym in symbols do
    code := code ++ s!"    {lb}\"{escapeC sym}\", {sym.length}, {toTokName sym}{rb},\n"
  code := code ++ s!"{rb};\n"
  code := code ++ s!"#define NUM_SYMBOLS {symbols.length}\n\n"

  -- Lexer 構造体
  code := code ++ s!"typedef struct {lb}\n"
  code := code ++ "    const char *source;\n"
  code := code ++ "    int pos;\n"
  code := code ++ "    int length;\n"
  code := code ++ "    int line;\n"
  code := code ++ "    int col;\n"
  code := code ++ s!"{rb} Lexer;\n\n"

  -- lexer_init
  code := code ++ s!"static void lexer_init(Lexer *lex, const char *source, int length) {lb}\n"
  code := code ++ "    lex->source = source;\n"
  code := code ++ "    lex->pos = 0;\n"
  code := code ++ "    lex->length = length;\n"
  code := code ++ "    lex->line = 1;\n"
  code := code ++ "    lex->col = 1;\n"
  code := code ++ s!"{rb}\n\n"

  -- skip_whitespace
  code := code ++ s!"static void skip_whitespace(Lexer *lex) {lb}\n"
  code := code ++ s!"    while (lex->pos < lex->length) {lb}\n"
  code := code ++ "        char c = lex->source[lex->pos];\n"
  code := code ++ s!"        if (c == ' ' || c == '\\t' || c == '\\r') {lb}\n"
  code := code ++ "            lex->pos++;\n"
  code := code ++ "            lex->col++;\n"
  code := code ++ s!"        {rb} else if (c == '\\n') {lb}\n"
  code := code ++ "            lex->pos++;\n"
  code := code ++ "            lex->line++;\n"
  code := code ++ "            lex->col = 1;\n"
  code := code ++ s!"        {rb} else {lb}\n"
  code := code ++ "            break;\n"
  code := code ++ s!"        {rb}\n"
  code := code ++ s!"    {rb}\n"
  code := code ++ s!"{rb}\n\n"

  -- next_token
  code := code ++ s!"static LexToken next_token(Lexer *lex) {lb}\n"
  code := code ++ "    skip_whitespace(lex);\n"
  code := code ++ s!"    LexToken tok = {lb}TOK_EOF, lex->source + lex->pos, 0, lex->line, lex->col{rb};\n\n"
  code := code ++ s!"    if (lex->pos >= lex->length) {lb}\n"
  code := code ++ "        return tok;\n"
  code := code ++ s!"    {rb}\n\n"
  code := code ++ "    const char *start = lex->source + lex->pos;\n"
  code := code ++ "    int start_col = lex->col;\n\n"

  -- 識別子 / キーワード判定
  code := code ++ "    /* Identifier or keyword */\n"
  code := code ++ s!"    if ((start[0] >= 'a' && start[0] <= 'z') ||\n"
  code := code ++ s!"        (start[0] >= 'A' && start[0] <= 'Z') ||\n"
  code := code ++ s!"        start[0] == '_') {lb}\n"
  code := code ++ "        int len = 1;\n"
  code := code ++ s!"        while (lex->pos + len < lex->length &&\n"
  code := code ++ s!"               ((start[len] >= 'a' && start[len] <= 'z') ||\n"
  code := code ++ s!"                (start[len] >= 'A' && start[len] <= 'Z') ||\n"
  code := code ++ s!"                (start[len] >= '0' && start[len] <= '9') ||\n"
  code := code ++ s!"                start[len] == '_')) {lb}\n"
  code := code ++ "            len++;\n"
  code := code ++ s!"        {rb}\n"
  code := code ++ "        /* Check keywords */\n"
  code := code ++ s!"        for (int i = 0; i < NUM_KEYWORDS; i++) {lb}\n"
  code := code ++ s!"            int klen = 0;\n"
  code := code ++ s!"            while (keywords[i].str[klen]) klen++;\n"
  code := code ++ s!"            if (klen == len && memcmp(start, keywords[i].str, len) == 0) {lb}\n"
  code := code ++ s!"                tok.type = keywords[i].token;\n"
  code := code ++ s!"                tok.start = start;\n"
  code := code ++ s!"                tok.length = len;\n"
  code := code ++ s!"                tok.col = start_col;\n"
  code := code ++ s!"                lex->pos += len;\n"
  code := code ++ s!"                lex->col += len;\n"
  code := code ++ s!"                return tok;\n"
  code := code ++ s!"            {rb}\n"
  code := code ++ s!"        {rb}\n"

  -- キーワードにマッチしなかった識別子
  code := code ++ "        /* Unknown identifier */\n"
  code := code ++ s!"        tok.type = -1;\n"
  code := code ++ "        tok.start = start;\n"
  code := code ++ "        tok.length = len;\n"
  code := code ++ "        tok.col = start_col;\n"
  code := code ++ "        lex->pos += len;\n"
  code := code ++ "        lex->col += len;\n"
  code := code ++ "        return tok;\n"
  code := code ++ s!"    {rb}\n\n"

  -- 数字リテラル
  code := code ++ "    /* Number literal */\n"
  code := code ++ s!"    if (start[0] >= '0' && start[0] <= '9') {lb}\n"
  code := code ++ "        int len = 1;\n"
  code := code ++ s!"        while (lex->pos + len < lex->length &&\n"
  code := code ++ s!"               start[len] >= '0' && start[len] <= '9') {lb}\n"
  code := code ++ "            len++;\n"
  code := code ++ s!"        {rb}\n"
  code := code ++ s!"        tok.type = -1;\n"
  code := code ++ "        tok.start = start;\n"
  code := code ++ "        tok.length = len;\n"
  code := code ++ "        tok.col = start_col;\n"
  code := code ++ "        lex->pos += len;\n"
  code := code ++ "        lex->col += len;\n"
  code := code ++ "        return tok;\n"
  code := code ++ s!"    {rb}\n\n"

  -- 記号の最長一致
  code := code ++ "    /* Symbol (longest match) */\n"
  code := code ++ "    int remaining = lex->length - lex->pos;\n"
  code := code ++ s!"    for (int i = 0; i < NUM_SYMBOLS; i++) {lb}\n"
  code := code ++ s!"        if (symbols[i].len <= remaining &&\n"
  code := code ++ s!"            memcmp(start, symbols[i].str, symbols[i].len) == 0) {lb}\n"
  code := code ++ "            tok.type = symbols[i].token;\n"
  code := code ++ "            tok.start = start;\n"
  code := code ++ "            tok.length = symbols[i].len;\n"
  code := code ++ "            tok.col = start_col;\n"
  code := code ++ "            lex->pos += symbols[i].len;\n"
  code := code ++ "            lex->col += symbols[i].len;\n"
  code := code ++ "            return tok;\n"
  code := code ++ s!"        {rb}\n"
  code := code ++ s!"    {rb}\n\n"

  -- 不明な文字
  code := code ++ "    /* Unknown character */\n"
  code := code ++ "    tok.type = -1;\n"
  code := code ++ "    tok.start = start;\n"
  code := code ++ "    tok.length = 1;\n"
  code := code ++ "    tok.col = start_col;\n"
  code := code ++ "    lex->pos++;\n"
  code := code ++ "    lex->col++;\n"
  code := code ++ "    return tok;\n"
  code := code ++ s!"{rb}\n\n"

  -- tokenize 関数
  code := code ++ s!"static int tokenize(const char *source, int length, int *out_tokens, int max_tokens) {lb}\n"
  code := code ++ "    Lexer lex;\n"
  code := code ++ "    lexer_init(&lex, source, length);\n"
  code := code ++ "    int count = 0;\n\n"
  code := code ++ s!"    while (1) {lb}\n"
  code := code ++ "        LexToken tok = next_token(&lex);\n"
  code := code ++ s!"        if (tok.type == TOK_EOF) break;\n"
  code := code ++ s!"        if (tok.type < 0) {lb}\n"
  code := code ++ "            fprintf(stderr, \"Lexer error at line %d, col %d: \"\n"
  code := code ++ "                    \"unexpected '%.*s'\\n\",\n"
  code := code ++ "                    tok.line, tok.col, tok.length, tok.start);\n"
  code := code ++ "            return -1;\n"
  code := code ++ s!"        {rb}\n"
  code := code ++ s!"        if (count >= max_tokens) {lb}\n"
  code := code ++ "            fprintf(stderr, \"Error: too many tokens\\n\");\n"
  code := code ++ "            return -1;\n"
  code := code ++ s!"        {rb}\n"
  code := code ++ "        out_tokens[count++] = tok.type;\n"
  code := code ++ s!"    {rb}\n"
  code := code ++ "    return count;\n"
  code := code ++ s!"{rb}\n"

  code