/* LR(1) Parser - Generated by LR1-generator */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Token types */
enum Token {
    TOK_PLUS,
    TOK_STAR,
    TOK_LPAREN,
    TOK_RPAREN,
    TOK_ID,
    TOK_EOF,
    NUM_TOKENS  /* = 6 */
};

static const char *token_names[] = {
    "+",
    "*",
    "(",
    ")",
    "id",
    "$"
};

#define NUM_NONTERMINALS 3

static const char *nonterminal_names[] = {
    "E",
    "T",
    "F",
};

#define NUM_STATES 22
#define NUM_PRODUCTIONS 6

/* Production rules: {lhs_index, rhs_length} */
static const struct { int lhs; int rhs_len; } productions[6] = {
    {0, 3},  /* E → E '+' T */
    {0, 1},  /* E → T */
    {1, 3},  /* T → T '*' F */
    {1, 1},  /* T → F */
    {2, 3},  /* F → '(' E ')' */
    {2, 1},  /* F → 'id' */
};

/*
 * Action table encoding:
 *   0        = error
 *   positive = shift (value - 1 = target state)
 *   -1       = accept
 *   < -1     = reduce (-(value + 2) = production index)
 */
static const int action_table[NUM_STATES][NUM_TOKENS] = {
    {0, 0, 5, 0, 6, 0},
    {7, 0, 0, 0, 0, -1},
    {-3, 8, 0, 0, 0, -3},
    {-5, -5, 0, 0, 0, -5},
    {0, 0, 12, 0, 13, 0},
    {-7, -7, 0, 0, 0, -7},
    {0, 0, 5, 0, 6, 0},
    {0, 0, 5, 0, 6, 0},
    {16, 0, 0, 17, 0, 0},
    {-3, 18, 0, -3, 0, 0},
    {-5, -5, 0, -5, 0, 0},
    {0, 0, 12, 0, 13, 0},
    {-7, -7, 0, -7, 0, 0},
    {-2, 8, 0, 0, 0, -2},
    {-4, -4, 0, 0, 0, -4},
    {0, 0, 12, 0, 13, 0},
    {-6, -6, 0, 0, 0, -6},
    {0, 0, 12, 0, 13, 0},
    {16, 0, 0, 22, 0, 0},
    {-2, 18, 0, -2, 0, 0},
    {-4, -4, 0, -4, 0, 0},
    {-6, -6, 0, -6, 0, 0},
};

static const int goto_table[NUM_STATES][NUM_NONTERMINALS] = {
    {1, 2, 3},
    {-1, -1, -1},
    {-1, -1, -1},
    {-1, -1, -1},
    {8, 9, 10},
    {-1, -1, -1},
    {-1, 13, 3},
    {-1, -1, 14},
    {-1, -1, -1},
    {-1, -1, -1},
    {-1, -1, -1},
    {18, 9, 10},
    {-1, -1, -1},
    {-1, -1, -1},
    {-1, -1, -1},
    {-1, 19, 10},
    {-1, -1, -1},
    {-1, -1, 20},
    {-1, -1, -1},
    {-1, -1, -1},
    {-1, -1, -1},
    {-1, -1, -1},
};

#define MAX_STACK 4096

typedef struct {
    int states[MAX_STACK];
    int top;
} ParserStack;

/*
 * Parse a token stream.
 * tokens: array of token IDs (enum Token values)
 * num_tokens: length of the token array (not counting EOF)
 * Returns: 0 on success, -1 on error
 */
int parse(const int *tokens, int num_tokens) {
    ParserStack stack;
    stack.top = 0;
    stack.states[0] = 0;  /* initial state */
    int pos = 0;

    while (1) {
        int state = stack.states[stack.top];
        int token = (pos < num_tokens) ? tokens[pos] : TOK_EOF;
        int act = action_table[state][token];

        if (act > 0) {
            /* Shift */
            int next_state = act - 1;
            if (++stack.top >= MAX_STACK) {
                fprintf(stderr, "Error: stack overflow\n");
                return -1;
            }
            stack.states[stack.top] = next_state;
            pos++;
        } else if (act < -1) {
            /* Reduce */
            int rule = -(act + 2);
            int rhs_len = productions[rule].rhs_len;
            int lhs = productions[rule].lhs;
            stack.top -= rhs_len;
            if (stack.top < 0) {
                fprintf(stderr, "Error: stack underflow\n");
                return -1;
            }
            int goto_state = goto_table[stack.states[stack.top]][lhs];
            if (goto_state < 0) {
                fprintf(stderr, "Error: invalid goto from state %d, nonterminal %s\n",
                        stack.states[stack.top], nonterminal_names[lhs]);
                return -1;
            }
            if (++stack.top >= MAX_STACK) {
                fprintf(stderr, "Error: stack overflow\n");
                return -1;
            }
            stack.states[stack.top] = goto_state;
        } else if (act == -1) {
            /* Accept */
            printf("Parse successful!\n");
            return 0;
        } else {
            /* Error */
            fprintf(stderr, "Syntax error at position %d: "
                    "unexpected token %s in state %d\n",
                    pos, token_names[token], state);
            return -1;
        }
    }
}


/* Lexer - Generated by LR1-generator */

typedef struct {
    int type;       /* enum Token value */
    const char *start;
    int length;
    int line;
    int col;
} LexToken;

/* Keyword table */
static const struct { const char *str; int token; } keywords[] = {
    {"id", TOK_ID},
};
#define NUM_KEYWORDS 1

/* Symbol table (longest first) */
static const struct { const char *str; int len; int token; } symbols[] = {
    {")", 1, TOK_RPAREN},
    {"+", 1, TOK_PLUS},
    {"*", 1, TOK_STAR},
    {"(", 1, TOK_LPAREN},
};
#define NUM_SYMBOLS 4

typedef struct {
    const char *source;
    int pos;
    int length;
    int line;
    int col;
} Lexer;

static void lexer_init(Lexer *lex, const char *source, int length) {
    lex->source = source;
    lex->pos = 0;
    lex->length = length;
    lex->line = 1;
    lex->col = 1;
}

static void skip_whitespace(Lexer *lex) {
    while (lex->pos < lex->length) {
        char c = lex->source[lex->pos];
        if (c == ' ' || c == '\t' || c == '\r') {
            lex->pos++;
            lex->col++;
        } else if (c == '\n') {
            lex->pos++;
            lex->line++;
            lex->col = 1;
        } else {
            break;
        }
    }
}

static LexToken next_token(Lexer *lex) {
    skip_whitespace(lex);
    LexToken tok = {TOK_EOF, lex->source + lex->pos, 0, lex->line, lex->col};

    if (lex->pos >= lex->length) {
        return tok;
    }

    const char *start = lex->source + lex->pos;
    int start_col = lex->col;

    /* Identifier or keyword */
    if ((start[0] >= 'a' && start[0] <= 'z') ||
        (start[0] >= 'A' && start[0] <= 'Z') ||
        start[0] == '_') {
        int len = 1;
        while (lex->pos + len < lex->length &&
               ((start[len] >= 'a' && start[len] <= 'z') ||
                (start[len] >= 'A' && start[len] <= 'Z') ||
                (start[len] >= '0' && start[len] <= '9') ||
                start[len] == '_')) {
            len++;
        }
        /* Check keywords */
        for (int i = 0; i < NUM_KEYWORDS; i++) {
            int klen = 0;
            while (keywords[i].str[klen]) klen++;
            if (klen == len && memcmp(start, keywords[i].str, len) == 0) {
                tok.type = keywords[i].token;
                tok.start = start;
                tok.length = len;
                tok.col = start_col;
                lex->pos += len;
                lex->col += len;
                return tok;
            }
        }
        /* Unknown identifier */
        tok.type = -1;
        tok.start = start;
        tok.length = len;
        tok.col = start_col;
        lex->pos += len;
        lex->col += len;
        return tok;
    }

    /* Number literal */
    if (start[0] >= '0' && start[0] <= '9') {
        int len = 1;
        while (lex->pos + len < lex->length &&
               start[len] >= '0' && start[len] <= '9') {
            len++;
        }
        tok.type = -1;
        tok.start = start;
        tok.length = len;
        tok.col = start_col;
        lex->pos += len;
        lex->col += len;
        return tok;
    }

    /* Symbol (longest match) */
    int remaining = lex->length - lex->pos;
    for (int i = 0; i < NUM_SYMBOLS; i++) {
        if (symbols[i].len <= remaining &&
            memcmp(start, symbols[i].str, symbols[i].len) == 0) {
            tok.type = symbols[i].token;
            tok.start = start;
            tok.length = symbols[i].len;
            tok.col = start_col;
            lex->pos += symbols[i].len;
            lex->col += symbols[i].len;
            return tok;
        }
    }

    /* Unknown character */
    tok.type = -1;
    tok.start = start;
    tok.length = 1;
    tok.col = start_col;
    lex->pos++;
    lex->col++;
    return tok;
}

static int tokenize(const char *source, int length, int *out_tokens, int max_tokens) {
    Lexer lex;
    lexer_init(&lex, source, length);
    int count = 0;

    while (1) {
        LexToken tok = next_token(&lex);
        if (tok.type == TOK_EOF) break;
        if (tok.type < 0) {
            fprintf(stderr, "Lexer error at line %d, col %d: "
                    "unexpected '%.*s'\n",
                    tok.line, tok.col, tok.length, tok.start);
            return -1;
        }
        if (count >= max_tokens) {
            fprintf(stderr, "Error: too many tokens\n");
            return -1;
        }
        out_tokens[count++] = tok.type;
    }
    return count;
}

/* Read entire file into malloc'd buffer. Returns length, or -1 on error. */
static int read_file(const char *path, char **out) {
    FILE *f = fopen(path, "rb");
    if (!f) { perror(path); return -1; }
    fseek(f, 0, SEEK_END);
    long sz = ftell(f);
    fseek(f, 0, SEEK_SET);
    *out = (char *)malloc(sz + 1);
    if (!*out) { fclose(f); return -1; }
    fread(*out, 1, sz, f);
    (*out)[sz] = '\0';
    fclose(f);
    return (int)sz;
}

int main(int argc, char **argv) {
    const char *input = NULL;
    int input_len = 0;
    char *file_buf = NULL;

    if (argc < 2) {
        fprintf(stderr, "Usage: %s <input-string-or-file>\n", argv[0]);
        return EXIT_FAILURE;
    }

    /* Try to open as file first, fall back to treating as string */
    int flen = read_file(argv[1], &file_buf);
    if (flen >= 0) {
        input = file_buf;
        input_len = flen;
    } else {
        /* Concatenate all arguments as input string */
        int total = 0;
        for (int i = 1; i < argc; i++) {
            int l = 0; while(argv[i][l]) l++;
            total += l + (i > 1 ? 1 : 0);
        }
        file_buf = (char *)malloc(total + 1);
        int pos = 0;
        for (int i = 1; i < argc; i++) {
            if (i > 1) file_buf[pos++] = ' ';
            int l = 0; while(argv[i][l]) file_buf[pos++] = argv[i][l++];
        }
        file_buf[pos] = '\0';
        input = file_buf;
        input_len = pos;
    }

    /* Tokenize */
    #define MAX_INPUT_TOKENS 65536
    int tokens[MAX_INPUT_TOKENS];
    int num_tokens = tokenize(input, input_len, tokens, MAX_INPUT_TOKENS);
    free(file_buf);

    if (num_tokens < 0) {
        return EXIT_FAILURE;
    }

    /* Parse */
    int result = parse(tokens, num_tokens);
    return (result == 0) ? EXIT_SUCCESS : EXIT_FAILURE;
}
