/* LR(1) Parser - Generated by LR1-generator */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Token types */
enum Token {
    TOK_PLUS,
    TOK_STAR,
    TOK_LPAREN,
    TOK_RPAREN,
    TOK_ID,
    TOK_EOF,
    NUM_TOKENS  /* = 6 */
};

static const char *token_names[] = {
    "+",
    "*",
    "(",
    ")",
    "id",
    "$"
};

#define NUM_NONTERMINALS 3

static const char *nonterminal_names[] = {
    "E",
    "T",
    "F",
};

#define NUM_STATES 22
#define NUM_PRODUCTIONS 6

/* Production rules: {lhs_index, rhs_length} */
static const struct { int lhs; int rhs_len; } productions[6] = {
    {0, 3},  /* E → E '+' T */
    {0, 1},  /* E → T */
    {1, 3},  /* T → T '*' F */
    {1, 1},  /* T → F */
    {2, 3},  /* F → '(' E ')' */
    {2, 1},  /* F → 'id' */
};

/*
 * Action table encoding:
 *   0        = error
 *   positive = shift (value - 1 = target state)
 *   -1       = accept
 *   < -1     = reduce (-(value + 2) = production index)
 */
static const int action_table[NUM_STATES][NUM_TOKENS] = {
    {0, 0, 5, 0, 6, 0},
    {7, 0, 0, 0, 0, -1},
    {-3, 8, 0, 0, 0, -3},
    {-5, -5, 0, 0, 0, -5},
    {0, 0, 12, 0, 13, 0},
    {-7, -7, 0, 0, 0, -7},
    {0, 0, 5, 0, 6, 0},
    {0, 0, 5, 0, 6, 0},
    {16, 0, 0, 17, 0, 0},
    {-3, 18, 0, -3, 0, 0},
    {-5, -5, 0, -5, 0, 0},
    {0, 0, 12, 0, 13, 0},
    {-7, -7, 0, -7, 0, 0},
    {-2, 8, 0, 0, 0, -2},
    {-4, -4, 0, 0, 0, -4},
    {0, 0, 12, 0, 13, 0},
    {-6, -6, 0, 0, 0, -6},
    {0, 0, 12, 0, 13, 0},
    {16, 0, 0, 22, 0, 0},
    {-2, 18, 0, -2, 0, 0},
    {-4, -4, 0, -4, 0, 0},
    {-6, -6, 0, -6, 0, 0},
};

static const int goto_table[NUM_STATES][NUM_NONTERMINALS] = {
    {1, 2, 3},
    {-1, -1, -1},
    {-1, -1, -1},
    {-1, -1, -1},
    {8, 9, 10},
    {-1, -1, -1},
    {-1, 13, 3},
    {-1, -1, 14},
    {-1, -1, -1},
    {-1, -1, -1},
    {-1, -1, -1},
    {18, 9, 10},
    {-1, -1, -1},
    {-1, -1, -1},
    {-1, -1, -1},
    {-1, 19, 10},
    {-1, -1, -1},
    {-1, -1, 20},
    {-1, -1, -1},
    {-1, -1, -1},
    {-1, -1, -1},
    {-1, -1, -1},
};

#define MAX_STACK 4096

typedef struct {
    int states[MAX_STACK];
    int top;
} ParserStack;

/*
 * Parse a token stream.
 * tokens: array of token IDs (enum Token values)
 * num_tokens: length of the token array (not counting EOF)
 * Returns: 0 on success, -1 on error
 */
int parse(const int *tokens, int num_tokens) {
    ParserStack stack;
    stack.top = 0;
    stack.states[0] = 0;  /* initial state */
    int pos = 0;

    while (1) {
        int state = stack.states[stack.top];
        int token = (pos < num_tokens) ? tokens[pos] : TOK_EOF;
        int act = action_table[state][token];

        if (act > 0) {
            /* Shift */
            int next_state = act - 1;
            if (++stack.top >= MAX_STACK) {
                fprintf(stderr, "Error: stack overflow\n");
                return -1;
            }
            stack.states[stack.top] = next_state;
            pos++;
        } else if (act < -1) {
            /* Reduce */
            int rule = -(act + 2);
            int rhs_len = productions[rule].rhs_len;
            int lhs = productions[rule].lhs;
            stack.top -= rhs_len;
            if (stack.top < 0) {
                fprintf(stderr, "Error: stack underflow\n");
                return -1;
            }
            int goto_state = goto_table[stack.states[stack.top]][lhs];
            if (goto_state < 0) {
                fprintf(stderr, "Error: invalid goto from state %d, nonterminal %s\n",
                        stack.states[stack.top], nonterminal_names[lhs]);
                return -1;
            }
            if (++stack.top >= MAX_STACK) {
                fprintf(stderr, "Error: stack overflow\n");
                return -1;
            }
            stack.states[stack.top] = goto_state;
        } else if (act == -1) {
            /* Accept */
            printf("Parse successful!\n");
            return 0;
        } else {
            /* Error */
            fprintf(stderr, "Syntax error at position %d: "
                    "unexpected token %s in state %d\n",
                    pos, token_names[token], state);
            return -1;
        }
    }
}

/* Example usage */
int main(void) {
    /* Provide your token stream here */
    int tokens[] = {TOK_PLUS, TOK_STAR, TOK_LPAREN, TOK_RPAREN, TOK_ID};
    int num_tokens = sizeof(tokens) / sizeof(tokens[0]);
    int result = parse(tokens, num_tokens);
    return (result == 0) ? EXIT_SUCCESS : EXIT_FAILURE;
}
